# Generated by Django 6.0 on 2026-01-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_participants_delete_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='event_images/event.png', null=True, upload_to='event_images'),
        ),
    ]
